package docsgen

import (
	"fmt"
	"sort"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

// GenCLI renders one page per visible command plus cli/index.md. Each page
// merges the catalog prose (Vietnamese, hand-written) with the facts read
// from the command tree: usage line, flags, parent and sub-commands. Hidden
// commands get no page; the index lists them under an internal-commands
// heading so the reader knows they exist.
func GenCLI(root *cobra.Command) (Files, error) {
	root.DisableAutoGenTag = true
	escapeAngleBrackets(root)
	files := Files{}
	walkCommands(root, func(c *cobra.Command) {
		if c.Hidden || anyHiddenAncestor(c) || (c != root && !c.IsAvailableCommand()) {
			return
		}
		files["cli/"+cliFile(c)+".md"] = cliPage(c)
	})
	files["cli/index.md"] = cliIndex(root)
	return files, nil
}

func cliFile(c *cobra.Command) string { return strings.ReplaceAll(c.CommandPath(), " ", "_") }

func cliPage(c *cobra.Command) []byte {
	frag, _ := LoadFragment("cli/" + cliFile(c))
	summary := frag.Summary
	if summary == "" {
		summary = c.Short
	}
	var b strings.Builder
	fmt.Fprintf(&b, "---\ntitle: %s\n---\n\n[Lệnh CLI](/reference/cli/) / `%s`\n\n# `%s`\n\n%s\n\n", c.CommandPath(), c.CommandPath(), c.CommandPath(), summary) //znf:allow-lang
	fmt.Fprintf(&b, "## Cú pháp\n\n```text\n%s\n```\n\n", c.UseLine())                                                                                           //znf:allow-lang
	if frag.Body != "" {
		b.WriteString(frag.Body + "\n\n")
	} else if c.Long != "" {
		b.WriteString(c.Long + "\n\n")
	}
	if !frag.HasSection("Cờ") { //znf:allow-lang
		if t := flagTable(c); t != "" {
			b.WriteString("## Cờ\n\n" + t + "\n") //znf:allow-lang
		}
	}
	if rel := relatedCommands(c); rel != "" {
		b.WriteString("## Lệnh liên quan\n\n" + rel + "\n") //znf:allow-lang
	}
	b.WriteString("<!-- Generated by zenify docs gen: prose from internal/docsgen/catalog, facts from the command tree. -->\n")
	return []byte(b.String())
}

// flagTable renders the command's own flags as a table; empty when none.
func flagTable(c *cobra.Command) string {
	var rows []string
	c.NonInheritedFlags().VisitAll(func(f *pflag.Flag) {
		if f.Name == "help" || f.Hidden {
			return
		}
		name := "`--" + f.Name + "`"
		if f.Shorthand != "" {
			name = "`-" + f.Shorthand + "`, " + name
		}
		usage := f.Usage
		if f.DefValue != "" && f.DefValue != "false" && f.DefValue != "0" && f.DefValue != "[]" {
			usage += " (mặc định `" + f.DefValue + "`)" //znf:allow-lang
		}
		rows = append(rows, fmt.Sprintf("| %s | %s |", name, escapeCell(usage)))
	})
	if len(rows) == 0 {
		return ""
	}
	return "| Cờ | Ý nghĩa |\n|---|---|\n" + strings.Join(rows, "\n") + "\n" //znf:allow-lang
}

// FlagNames lists the command's own visible flags; the catalog test uses it
// to check a hand-written flags table covers every flag.
func FlagNames(c *cobra.Command) []string {
	var out []string
	c.NonInheritedFlags().VisitAll(func(f *pflag.Flag) {
		if f.Name != "help" && !f.Hidden {
			out = append(out, f.Name)
		}
	})
	return out
}

func relatedCommands(c *cobra.Command) string {
	var rows []string
	if p := c.Parent(); p != nil && !p.Hidden {
		rows = append(rows, fmt.Sprintf("- [%s](./%s): %s", p.CommandPath(), cliFile(p), shortOf(p)))
	}
	for _, s := range c.Commands() {
		if s.Hidden || !s.IsAvailableCommand() {
			continue
		}
		rows = append(rows, fmt.Sprintf("- [%s](./%s): %s", s.CommandPath(), cliFile(s), shortOf(s)))
	}
	if len(rows) == 0 {
		return ""
	}
	return strings.Join(rows, "\n") + "\n"
}

// shortOf prefers the catalog summary over cobra's Short.
func shortOf(c *cobra.Command) string {
	if f, ok := LoadFragment("cli/" + cliFile(c)); ok && f.Summary != "" {
		return f.Summary
	}
	return c.Short
}

func cliIndex(root *cobra.Command) []byte {
	var visible, hidden []*cobra.Command
	walkCommands(root, func(c *cobra.Command) {
		if c == root {
			return
		}
		if c.Hidden || anyHiddenAncestor(c) {
			hidden = append(hidden, c)
		} else if c.IsAvailableCommand() {
			visible = append(visible, c)
		}
	})
	byPath := func(s []*cobra.Command) {
		sort.Slice(s, func(i, j int) bool { return s[i].CommandPath() < s[j].CommandPath() })
	}
	byPath(visible)
	byPath(hidden)

	var b strings.Builder
	b.WriteString("---\ntitle: Lệnh CLI\n---\n\n# Lệnh CLI\n\n") //znf:allow-lang
	if frag, ok := LoadFragment("cli/index"); ok {
		if frag.Summary != "" {
			b.WriteString(frag.Summary + "\n\n")
		}
		if frag.Body != "" {
			b.WriteString(frag.Body + "\n\n")
		}
	}
	b.WriteString("## Tất cả lệnh\n\n| Lệnh | Mô tả |\n|---|---|\n") //znf:allow-lang
	for _, c := range visible {
		fmt.Fprintf(&b, "| [%s](./%s) | %s |\n", c.CommandPath(), cliFile(c), escapePipe(shortOf(c)))
	}
	if len(hidden) > 0 {
		b.WriteString("\n## Lệnh nội bộ\n\nHook và skill gọi các lệnh này; bạn không cần gõ tay nên chúng không có trang riêng.\n\n| Lệnh | Mô tả |\n|---|---|\n") //znf:allow-lang
		for _, c := range hidden {
			fmt.Fprintf(&b, "| `%s` | %s |\n", c.CommandPath(), escapePipe(c.Short))
		}
	}
	b.WriteString("\n<!-- Generated by zenify docs gen: intro from internal/docsgen/catalog/cli/index.md, table from the command tree. -->\n")
	return []byte(b.String())
}

// escapeAngleBrackets backslash-escapes literal "<"/">" in Short/Long text
// (e.g. "R<N>.md", "--port <key>") so markdown-it does not parse them as a
// bare HTML tag — Vue's compiler then fails the whole build on an unclosed
// element. CommonMark treats "\<" as a literal "<", so this only changes how
// the character round-trips through markdown, not what the reader sees.
func escapeAngleBrackets(root *cobra.Command) {
	walkCommands(root, func(c *cobra.Command) {
		c.Short = escapeAngle(c.Short)
		c.Long = escapeAngle(c.Long)
	})
}

func walkCommands(c *cobra.Command, fn func(*cobra.Command)) {
	fn(c)
	for _, sub := range c.Commands() {
		walkCommands(sub, fn)
	}
}

func anyHiddenAncestor(c *cobra.Command) bool {
	for p := c.Parent(); p != nil; p = p.Parent() {
		if p.Hidden {
			return true
		}
	}
	return false
}
