package docsgen

import (
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"github.com/spf13/cobra"
)

func fixtureRoot() *cobra.Command {
	root := &cobra.Command{Use: "zenify", Short: "root"}
	a := &cobra.Command{Use: "alpha", Short: "lệnh alpha", Run: func(*cobra.Command, []string) {}} //znf:allow-lang
	a.Flags().Bool("dry-run", false, "chỉ in")                                                     //znf:allow-lang
	b := &cobra.Command{Use: "beta", Short: "lệnh beta"}                                           //znf:allow-lang
	b.AddCommand(&cobra.Command{Use: "sub", Short: "beta sub", Run: func(*cobra.Command, []string) {}})
	h := &cobra.Command{Use: "hidden-one", Short: "ẩn", Hidden: true, Run: func(*cobra.Command, []string) {}} //znf:allow-lang
	root.AddCommand(a, b, h)
	return root
}

func TestGenCLI_OnePagePerVisibleCommand(t *testing.T) {
	files, err := GenCLI(fixtureRoot())
	if err != nil {
		t.Fatal(err)
	}
	var got []string
	for p := range files {
		got = append(got, p)
	}
	sort.Strings(got)
	want := []string{"cli/index.md", "cli/zenify.md", "cli/zenify_alpha.md", "cli/zenify_beta.md", "cli/zenify_beta_sub.md"}
	if strings.Join(got, ",") != strings.Join(want, ",") {
		t.Fatalf("files = %v, want %v", got, want)
	}
	if _, ok := files["cli/zenify_hidden-one.md"]; ok {
		t.Fatal("hidden command must not get a page")
	}
}

func TestGenCLI_FrontmatterAndNoAutoGenTag(t *testing.T) {
	files, _ := GenCLI(fixtureRoot())
	page := string(files["cli/zenify_alpha.md"])
	if !strings.HasPrefix(page, "---\ntitle: zenify alpha\n---\n") {
		t.Fatalf("missing frontmatter: %q", page[:60])
	}
	if strings.Contains(page, "Auto generated by spf13/cobra") {
		t.Fatal("auto-gen tag must be disabled")
	}
	if !strings.Contains(page, "--dry-run") {
		t.Fatal("flags missing")
	}
	// links point at sibling pages without .md → VitePress clean URLs
	if strings.Contains(page, "](zenify.md)") || !strings.Contains(page, "](./zenify)") {
		t.Fatalf("link handler not applied: %q", page)
	}
}

func TestGenCLI_IndexListsHidden(t *testing.T) {
	files, _ := GenCLI(fixtureRoot())
	idx := string(files["cli/index.md"])
	for _, want := range []string{"| [zenify alpha](./zenify_alpha) | lệnh alpha |", "## Lệnh nội bộ (hook)", "| `zenify hidden-one` | ẩn |"} { //znf:allow-lang
		if !strings.Contains(idx, want) {
			t.Errorf("index missing %q\n%s", want, idx)
		}
	}
}

func TestGenCLI_EscapesAngleBrackets(t *testing.T) {
	root := &cobra.Command{Use: "zenify", Short: "root"}
	c := &cobra.Command{Use: "gamma", Short: "ghi docs/releases/R<N>.md", Run: func(*cobra.Command, []string) {}}
	root.AddCommand(c)
	files, err := GenCLI(root)
	if err != nil {
		t.Fatal(err)
	}
	for _, path := range []string{"cli/zenify_gamma.md", "cli/index.md"} {
		page := string(files[path])
		if strings.Contains(page, "R<N>.md") {
			t.Fatalf("%s: unescaped angle bracket would break the Vue markdown compiler: %q", path, page)
		}
		if !strings.Contains(page, `R\<N\>.md`) {
			t.Fatalf("%s: expected backslash-escaped angle brackets, got: %q", path, page)
		}
	}
}

func TestWriteAndCheck(t *testing.T) {
	dir := t.TempDir()
	files, _ := GenCLI(fixtureRoot())
	if err := Write(dir, files); err != nil {
		t.Fatal(err)
	}
	if diff := Check(dir, files); len(diff) != 0 {
		t.Fatalf("fresh write should match, got %v", diff)
	}
	// modified file → reported
	p := filepath.Join(dir, "cli", "zenify_alpha.md")
	b, _ := os.ReadFile(p)
	_ = os.WriteFile(p, append(b, 'x'), 0o644)
	// stray file → reported
	_ = os.WriteFile(filepath.Join(dir, "cli", "stray.md"), []byte("x"), 0o644)
	diff := Check(dir, files)
	sort.Strings(diff)
	if strings.Join(diff, ",") != "cli/stray.md,cli/zenify_alpha.md" {
		t.Fatalf("diff = %v", diff)
	}
}
