package docsgen

import (
	"fmt"
	"strings"

	"github.com/ZenifyAIContactCenter/zenify-kit/internal/apply"
)

// GenHooks renders hooks.md from the kit's hook table (apply.HookSpecs) plus
// the git-guard hook, which `zenify guard install` wires separately (FR-2.3).
func GenHooks(specs []apply.HookSpec) Files {
	var b strings.Builder
	b.WriteString("---\ntitle: Hook\n---\n\n# Hook\n\n") //znf:allow-lang
	if frag, ok := LoadFragment("hooks"); ok && (frag.Summary != "" || frag.Body != "") {
		if frag.Summary != "" {
			b.WriteString(frag.Summary + "\n\n")
		}
		if frag.Body != "" {
			b.WriteString(frag.Body + "\n\n")
		}
	} else {
		b.WriteString("`zenify up` ghi các hook sau vào `~/.claude/settings.json`; mỗi hook là một lệnh `zenify hooks-run <id>` (fail-open, chỉ chạy trong workspace).\n\n") //znf:allow-lang
	}
	b.WriteString("## Bảng hook\n\n")                                           //znf:allow-lang
	b.WriteString("| Event | Matcher | Lệnh | Mục đích |\n|---|---|---|---|\n") //znf:allow-lang
	for _, s := range specs {
		m := "—"
		if s.Matcher != "" {
			m = "`" + escapeCell(s.Matcher) + "`"
		}
		fmt.Fprintf(&b, "| %s | %s | `zenify hooks-run %s` | %s |\n", s.Event, m, s.ID, escapeCell(s.Purpose))
	}
	b.WriteString("| PreToolUse | `Bash` | `zenify git-guard` (cài bằng `zenify guard install`) | Chặn commit/push/merge vào nhánh deploy |\n\n")             //znf:allow-lang
	b.WriteString("<!-- Generated by zenify docs gen: intro from internal/docsgen/catalog/hooks.md, table from the hook specs embedded in the binary. -->\n") //znf:allow-lang
	return Files{"hooks.md": []byte(b.String())}
}
