package docsgen

import (
	"fmt"
	"io/fs"
	"path"
	"sort"
	"strings"
)

// GenSkills renders skills/<name>.md (znf + coding), agents/<name>.md and
// both indexes. Prose comes from the catalog; the invocation line and the
// user-only warning come from the frontmatter. Skill bodies are agent-read
// and are never copied (FR-2.2).
func GenSkills(znf, coding fs.FS) (Files, error) {
	files := Files{}
	var skillRows, agentRows []string

	addSkill := func(fm Frontmatter, ns string) {
		call := "/" + ns + fm.Name
		if fm.ArgumentHint != "" {
			call += " " + fm.ArgumentHint
		}
		frag, _ := LoadFragment("skills/" + fm.Name)
		raw := frag.Summary // hand-written: already markdown-safe
		summary := raw
		if raw == "" {
			raw = fm.Description
			summary = escapeAngle(raw)
		}
		var b strings.Builder
		fmt.Fprintf(&b, "---\ntitle: /%s%s\n---\n\n[Skill](/reference/skills/) / `/%s%s`\n\n# `%s`\n\n%s\n\n", ns, fm.Name, ns, fm.Name, call, summary) //znf:allow-lang
		fmt.Fprintf(&b, "## Cách gọi\n\n```text\n%s\n```\n\n", call)                                                                                    //znf:allow-lang
		if fm.DisableModelInvocation {
			b.WriteString("::: warning Chỉ bạn gõ được\nAgent không tự chạy skill này, chỉ đề xuất. Bạn gõ lệnh khi thấy cần.\n:::\n\n") //znf:allow-lang
		}
		if frag.Body != "" {
			b.WriteString(frag.Body + "\n\n")
		}
		b.WriteString("<!-- Generated by zenify docs gen: prose from internal/docsgen/catalog, invocation from the SKILL.md frontmatter embedded in the binary. -->\n")
		files["skills/"+fm.Name+".md"] = []byte(b.String())
		skillRows = append(skillRows, fmt.Sprintf("| [/%s%s](./%s) | %s |", ns, fm.Name, fm.Name, escapeCell(firstSentence(raw))))
	}

	if err := eachSkill(znf, "skills", func(fm Frontmatter) { addSkill(fm, "znf:") }); err != nil {
		return nil, err
	}
	if err := eachSkill(coding, ".", func(fm Frontmatter) { addSkill(fm, "") }); err != nil {
		return nil, err
	}
	agents, _ := fs.ReadDir(znf, "agents")
	for _, e := range agents {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".md") {
			continue
		}
		b, err := fs.ReadFile(znf, "agents/"+e.Name())
		if err != nil {
			return nil, err
		}
		fm, err := ParseFrontmatter(b)
		if err != nil {
			return nil, fmt.Errorf("agents/%s: %w", e.Name(), err)
		}
		frag, _ := LoadFragment("agents/" + fm.Name)
		raw := frag.Summary
		summary := raw
		if raw == "" {
			raw = fm.Description
			summary = escapeAngle(raw)
		}
		var p strings.Builder
		fmt.Fprintf(&p, "---\ntitle: agent %s\n---\n\n[Agent](/reference/agents/) / `%s`\n\n# Agent `%s`\n\n%s\n\n", fm.Name, fm.Name, fm.Name, summary) //znf:allow-lang
		if frag.Body != "" {
			p.WriteString(frag.Body + "\n\n")
		}
		p.WriteString("<!-- Generated by zenify docs gen: prose from internal/docsgen/catalog, name from the agent frontmatter embedded in the binary. -->\n")
		files["agents/"+fm.Name+".md"] = []byte(p.String())
		agentRows = append(agentRows, fmt.Sprintf("| [%s](./%s) | %s |", fm.Name, fm.Name, escapeCell(firstSentence(raw))))
	}
	sort.Strings(skillRows)
	sort.Strings(agentRows)
	files["skills/index.md"] = index("Skill", "skills/index", "Skill `znf:*` gọi bằng `/znf:<name>`; coding skill gọi bằng `/<name>` sau `zenify skills install`.", skillRows) //znf:allow-lang
	files["agents/index.md"] = index("Agent", "agents/index", "Agent được skill dispatch qua Agent tool; bạn không gọi trực tiếp.", agentRows)                                 //znf:allow-lang
	return files, nil
}

// eachSkill visits <dir>/<name>/SKILL.md; names starting with "_" are shared references, not skills.
func eachSkill(fsys fs.FS, dir string, fn func(Frontmatter)) error {
	entries, err := fs.ReadDir(fsys, dir)
	if err != nil {
		return nil // no such tree → nothing to render
	}
	for _, e := range entries {
		if !e.IsDir() || strings.HasPrefix(e.Name(), "_") {
			continue
		}
		b, err := fs.ReadFile(fsys, path.Join(dir, e.Name(), "SKILL.md"))
		if err != nil {
			continue
		}
		fm, err := ParseFrontmatter(b)
		if err != nil {
			return fmt.Errorf("%s/%s/SKILL.md: %w", dir, e.Name(), err)
		}
		fn(fm)
	}
	return nil
}

// index renders an index page: title, catalog intro (fallback to the given
// default), then the name/summary table.
func index(title, fragRel, fallbackIntro string, rows []string) []byte {
	var b strings.Builder
	fmt.Fprintf(&b, "---\ntitle: %s\n---\n\n# %s\n\n", title, title)
	if frag, ok := LoadFragment(fragRel); ok && (frag.Summary != "" || frag.Body != "") {
		if frag.Summary != "" {
			b.WriteString(frag.Summary + "\n\n")
		}
		if frag.Body != "" {
			b.WriteString(frag.Body + "\n\n")
		}
	} else {
		b.WriteString(fallbackIntro + "\n\n")
	}
	b.WriteString("## Danh sách\n\n| Tên | Mô tả |\n|---|---|\n") //znf:allow-lang
	for _, r := range rows {
		b.WriteString(r + "\n")
	}
	return []byte(b.String())
}

func firstSentence(s string) string {
	if i := strings.Index(s, ". "); i > 0 {
		return s[:i+1]
	}
	return s
}
