# This file was generated by GoReleaser. DO NOT EDIT.
cask "zenify" do
  version "0.9.0"

  on_macos do
    on_arm do
      sha256 "7cca1f8f0dba52f81ab7c122f00ea8563ac247295503bd4be5fca89648132bc0"
      url "https://github.com/ZenifyAIContactCenter/zenify-kit/releases/download/v#{version}/zenify_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e57df7e13cfca8704fcbdc0f068344acd35e1bc2f294cacf4c80854bc356189d"
      url "https://github.com/ZenifyAIContactCenter/zenify-kit/releases/download/v#{version}/zenify_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "724dc1fd54bfc5f08e122891de307dbb493afdafe3cd60f791363128c17efc62"
      url "https://github.com/ZenifyAIContactCenter/zenify-kit/releases/download/v#{version}/zenify_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "25aeed0959e9c2716939daf4783ea84a7e522a6a44a61c7dda31c99fead28522"
      url "https://github.com/ZenifyAIContactCenter/zenify-kit/releases/download/v#{version}/zenify_linux_amd64.tar.gz"
    end
  end

  name "zenify"
  desc "Portable zenify workspace toolkit"
  homepage "https://github.com/ZenifyAIContactCenter/zenify-kit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zenify"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/zenify"]
    end
  end

  # No zap stanza required
end
