# This file was generated by GoReleaser. DO NOT EDIT.
cask "zenify" do
  version "0.5.0"

  on_macos do
    on_arm do
      sha256 "c2efea403cc928de909946152586860727f3e975187bec89662070cab379dc91"
      url "https://github.com/ZenifyAIContactCenter/zenify-kit/releases/download/v#{version}/zenify_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9f6b5e0d1f26caad7cc22b9bbf2669f8ec2ef598756394a5bc5512720298ddc4"
      url "https://github.com/ZenifyAIContactCenter/zenify-kit/releases/download/v#{version}/zenify_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1e04e1da4ead6869a0f436df41efcb1f84aecb99d391828a57221d1e66286e3b"
      url "https://github.com/ZenifyAIContactCenter/zenify-kit/releases/download/v#{version}/zenify_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8f15f770e4abc61fd897261b71602371b938a0b34ea916abb6898bad9035555a"
      url "https://github.com/ZenifyAIContactCenter/zenify-kit/releases/download/v#{version}/zenify_linux_amd64.tar.gz"
    end
  end

  name "zenify"
  desc "Portable zenify workspace toolkit"
  homepage "https://github.com/ZenifyAIContactCenter/zenify-kit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zenify"

  # No zap stanza required
end
