# This file was generated by GoReleaser. DO NOT EDIT.
cask "zenify" do
  version "0.23.0"

  on_macos do
    on_arm do
      sha256 "43ecdb9c72a15c11ac6a28ca53a7ad0587be739a03a2f8f07a8c50982265deda"
      url "https://github.com/ZenifyAIContactCenter/zenify-kit/releases/download/v#{version}/zenify_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "300d59be934513c1a07da490ca4e579b88135037969d03068535d5d05e254254"
      url "https://github.com/ZenifyAIContactCenter/zenify-kit/releases/download/v#{version}/zenify_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7b92c97418cc1b9545b3365ef39529d5ba45a43555a614e1419a07a50e10bb36"
      url "https://github.com/ZenifyAIContactCenter/zenify-kit/releases/download/v#{version}/zenify_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2dec6a2a10f15aaa9614d5fda8117c0b23e994d40dc2fb524fb63d9ddc787063"
      url "https://github.com/ZenifyAIContactCenter/zenify-kit/releases/download/v#{version}/zenify_linux_amd64.tar.gz"
    end
  end

  name "zenify"
  desc "Portable zenify workspace toolkit"
  homepage "https://github.com/ZenifyAIContactCenter/zenify-kit"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "gh",
    ]

  binary "zenify"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/zenify"]
    end
    system_command "#{staged_path}/zenify", args: ["skills", "sync"]
  end

  # No zap stanza required
end
